[tool.poetry]
name = "cv"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.3"
jinja2 = "^3.1.6"
click = "^8.3.0"


[tool.black]
line-length = 120
include = "^/render$|\\.py$"
